### ISSUE TITLE
Settings plugin does not work with MvvmCross 3.2

### ISSUE THREAD

**Issue by kjeremy** [Cheesebaron/Cheesebaron.MvxPlugins#23]
I get the following from Nuget after I update my project's core PCL to the new profile as required by the latest mvvmcross:

Could not install package 'Cheesebaron.MvxPlugins.Settings 1.0.2'. You are trying to install this package into a project that targets 'portable-net45+win+wpa81+MonoAndroid10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Cheesebaron** [comment]
This should have been fixed.
