### ISSUE TITLE
Settings nuget package for Touch

### ISSUE THREAD

**Issue by mgjhl** [Cheesebaron/Cheesebaron.MvxPlugins#24]
So here's what i've experienced: I install the Settings nuget package in my core, droid and touch project. It works on Android. But for my touch project, i cannot instantiate my viewmodel, as it uses the ISettings service. Likewise, Mvx.CanResolve<ISettings>() returns false.

If i pull the code here from github, and add it as regular projects which i reference, everything works fine.

It seems to me there might be a problem with the nuget package?

**Comment by Cheesebaron** [comment]
Reopen if still an issue.
