### ISSUE TITLE
Add licensing to FormsPresenters

### ISSUE THREAD

**Issue by Cheesebaron** [Cheesebaron/Cheesebaron.MvxPlugins#40]
Add MIT license to FormsPresenters code.

**Comment by MarcosCobena** [comment]
@Cheesebaron I've just added my-self to the licensing headers, as contributor. Let me know please if it doesn't fit well for you. Thanks!

**Comment by Cheesebaron** [comment]
Not a problem. Thanks for your contributions :+1:
