### ISSUE TITLE
Sms Plugin built in Debug - Windows Phone

### ISSUE THREAD

**Issue by The-Bytemaster** [Cheesebaron/Cheesebaron.MvxPlugins#42]
I just did the pre-scan before submitting the new version of my app to the Windows Phone store, and it gave the error "The binary Cheesebaron.MvxPlugins.SMS.dll is built in debug mode."

Apparently, Windows Phone Store will not allow applications to be submitted if one of the dependencies was built in debug mode.

**Comment by The-Bytemaster** [comment]
My mistake -- Windows Common is not supported for SMS plugin.  I will try and build one.

**Comment by Cheesebaron** [comment]
You are very welcome to submit a pull request.
