### ISSUE TITLE
Settings plugin: Missing Bootstrap for iOS if added via NuGet

### ISSUE THREAD

**Issue by JanZeman** [Cheesebaron/Cheesebaron.MvxPlugins#50]
Hello, I did a quick test of Settings plugin - both for Android and iOS. For Android all worked like a charm but after I added Settings plugin to the iOS project it failed. I realised the SettingsPluginBootstrap.cs and its Bootstrap folder are missing. After I created / added those manually the plugin loaded. Everybody will easily find a fix for this but if fixed it will save peoples' time I guess.

Have a great day :)
Jan

**Comment by Cheesebaron** [comment]
https://github.com/Cheesebaron/Cheesebaron.MvxPlugins/blob/master/nuspec/Cheesebaron.MvxPlugins.Settings.nuspec#L91

You are right, it is because it is put in MonoTouch instead of Xamarin.iOS10. Thanks for point this out :+1:

**Comment by JanZeman** [comment]
You are fast, Tomasz :+1: 
Thank you :)

**Comment by Cheesebaron** [comment]
Nuget will be up soon :)

**Comment by Cheesebaron** [comment]
Nuget is up. Symbol sources should also be up for all nugets. Enjoy :)
