### ISSUE TITLE
Cheesebaron.MvxPlugins-master/Samples/FormsPresenters Upgrade or Fork VS2015RC

### ISSUE THREAD

**Issue by PeterBurke** [Cheesebaron/Cheesebaron.MvxPlugins#51]
I have been working with the very latest stable releases and Visual Studio 2015. VS went RC late April and I expect the final release to be out by the end of July. Prior to the RC, there was no Xamarin Support for Windows Phone 8.1 only Windows Phone 8.0 via Siliverlight 8.0. With the release of the RC  we now have support for WP 8.1 via Silverlight 8.1 and support for WP 8.0 has been dropped.

Somewhat inconvenient I know, it means you need to retool for WP 8.1 but WP currently has low market share!

Microsoft created a new PCL Profile for Shared Projects that includes WP 8.1 as well as Windows 8.1. At some stage I might add the ViewPresenter for Windows 8.1, but there is a much more interesting Windows 10 Universal App coming with Windows 10 end of July. This target is slated to run on both Mobile devices and the desktop. I have joined the Xamarin preview group for W10 UAP.

**Right now I have taken the Cheesebaron.MvxPlugins-master/Samples/FormsPresenters set and upgraded NeGet packages as well as changing the PCL to the new profile and changed the Windows Phone over to 8.1.** The only files touched that are relevant are the packages.config and 3 Movies.*.csproj files. All three phone platforms I have tested and work.

***I can email the zip of these files, 12kb (Fork & pull), or I could get a shared access and push.***

We need to be mindful that this change will be somewhat disruptive for developers still on VS 2013. However what I am working on is important as it will provide a set of starter VS Templates for various combinations of components one would like in a Xamarin Universal App and It would help to have a stable set of NuGet Packages including CheesBarron.

Things will get quite hot after the Windows 10 release.

**Comment by Cheesebaron** [comment]
Fork and pull. I will merge it into another branch. Although I don't have VS2015 nor in the preview, so I won't be able to build it and create a nuget of the new stuff, maybe you can help here?

**Comment by PeterBurke** [comment]
Yes

I will work on it and keep in touch.

Best

Peter Burke

**Comment by PeterBurke** [comment]
Hi Tomaz

I have forked MvxPlugins and I have done an extensive analysis. I am in the process of pushing relatively minor changes up to the Fork as well as Pulling any of your changes, none so far.

Actually it seems that the changes I am making, primarily a change in PCL profile, will not break anything for people still on VS2013. I have put a lot of work into an MD file documenting the pull request that I will send to you, it explains what is happening in VS 2015 and why the changes are necessary.

In relation to the NuSpec I have determined something else that will require a different NuSpec for what I am trying to achieve.

Back in March I started with a zip clone of the entire MvxPlugins and what I wanted was MvvMCross working with Xamarin Forms that uses  XAML rather than c# to define forms. I have been working with XAML for years and as far as I am concerned it is a big productivity boost once you get the hang of it. It is even better if you can also use Blend, but alas Xamarin XAML is not quite the same. They say the problem can be overcome with a different schema in Blend.

As an aside you should be aware that Microsoft released their "Universal App" spec a year or so back. The press is implying that it is for Windows 10, but it has been around long enough for it to already be on your machine running VS 2013. The XAML provides a way where you can target a wide range screen sizes and tell the layout engine to reposition elements say either underneath or to the right depending on the size of the screen. In HTML Css3.0 has a similar concept known as media queries. So as part of the VS 2015 RC, MS and Xamarin got together to add a new target that we should now support. This target is the Universal App, it will run on Windows 8 and also Windows Phone 8.1 without using Silverlight. Xamarin  XAML support for UAP is rather patchy, but Xamarin are releasing another round of improvements next week. I will attempt to write a FormsPresenter and a Sample for this target in due course. Again it should still be possible to compile and test this new target from VS 2013.

OK so now for the NuSpec. When I started the NuSpec was creating problems for me and that is why I pulled down a Zip of your works and removed the NuGet references replacing them with a direct reference.

Now when I look at the NuSpec I noticed that it was copying source files like FirstPage.cs into the target. Unfortunately that is not going to be helpful when we are working in XAML. In fact I was bamboozled when I had everything working and seemingly without reason there compilation errors all over the place. Eventually I removed the additional files, but I had no idea where they came from.

Apart from that though, as I said the FormsPresenters work well with XAML, but I will need a second package NuSpec. Ideally within the root MvxPlugins.

Best

Peter Burke
