### ISSUE TITLE
Can not update a value to null

### ISSUE THREAD

**Issue by softlion** [Cheesebaron/Cheesebaron.MvxPlugins#55]
in AddOrUpdateValue<T>, the line:

            var type = value.GetType();

crashes if value is null.
It should be replaced with:

        public bool AddOrUpdateValue<T>(string key, T value = default(T))
        {
            if(string.IsNullOrEmpty(key))
                throw new ArgumentException("Key must have a value", "key");

            var type = typeof(T);

**Comment by Cheesebaron** [comment]
Why would you want to update the value to null? Why not just remove the setting entirely?

**Comment by softlion** [comment]
Well currently the plugin crashes.
I just make sure it won't.

B.

Le dimanche 28 juin 2015, Tomasz Cielecki <notifications@github.com> a
écrit :
