### ISSUE TITLE
DeviceInfo.WindowsUWP Not actually supporting UWP

### ISSUE THREAD

**Issue by JSalazar88** [Cheesebaron/Cheesebaron.MvxPlugins#56]
The nuspec file for DeviceInfo doesn't actually use the WindowsUWP project for anything.

The ability of a UWP MvvmCross UI application to consume this nuget successfully via Bootstrap.cs class declaration relies on the WindowsCommon lib, not WindowsUWP.

**Comment by Cheesebaron** [comment]
And using the stuff in WindowsCommon does not work?

The WindowsUWP project is pretty empty right now.
