### ISSUE TITLE
MvvmCross beta-8 support

### ISSUE THREAD

**Issue by SlyNet** [Cheesebaron/Cheesebaron.MvxPlugins#57]
In that beta core packages were renamed, so updating of references is needed

**Comment by Cheesebaron** [comment]
Calm down, it has been less than 24 hours since the release. I will update, unlike @aritchie's plugins. Wink wink, nudge nudge

**Comment by aritchie** [comment]
Bah... unnecessary,  Even @martijn00 agrees :) https://github.com/aritchie/userdialogs/issues/85#issuecomment-157368139 

Mvx.RegisterSingleton< IUserDialogs >(() => UserDialogs.Instance);

I'll think about it if there is enough to demand and once you guys have all of the refactoring done

**Comment by SergioZgz** [comment]
@aritchie +1

**Comment by Cheesebaron** [comment]
Plugins have been updated for the 4.0.0 stable release. Enjoy :)
