### ISSUE TITLE
Getting this!!!

### ISSUE THREAD

**Issue by rcbeyra** [Cheesebaron/Cheesebaron.MvxPlugins#60]
MvvmCross.Platform.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.Platform.iOS.Views.IMvxIosModalHost

**Comment by Cheesebaron** [comment]
OH NO! What do you want me to do about it?

**Comment by rcbeyra** [comment]
Do I have to resolve that in my appdelegate to use it??

**Comment by Cheesebaron** [comment]
IMvxIosModalHost has what to do with my code?

**Comment by rcbeyra** [comment]
I know you have nothing to do with it, but maybe you can help me because calling this fail.
public SmsTask()
        {
            _modalHost = Mvx.Resolve<IMvxIosModalHost>();
        }

**Comment by rcbeyra** [comment]
_modalHost = Mvx.Resolve<IMvxIosModalHost>();

**Comment by rcbeyra** [comment]
_modalHost = Mvx.Resolve IMvxIosModalHost ();

**Comment by Cheesebaron** [comment]
Try using MvxIosModalNavSupportPresenter or whatever it is called.
