### ISSUE TITLE
Connectivity IsConnected on Android only correct set when you change the state

### ISSUE THREAD

**Issue by NPadrutt** [Cheesebaron/Cheesebaron.MvxPlugins#61]
Hi
first of all, thanks for the plugins! :)

I had some issues with the version 2.1 of the connectivity plugin on Android. I noticed that all the properties are false when you start the app even though I have an internet connection via cellular. When I 
disable and enable my mobile connection it turns correctly to true, but is false after the next restart.
Also, when I'm in the app and start wlan it turns to true correctly as well.

I've found the same issue on 2.0.1 version of the plugin. 

I have an HTC 10 with Android 6.0.1

**Comment by Cheesebaron** [comment]
This should be handled here: https://github.com/Cheesebaron/Cheesebaron.MvxPlugins/blob/master/Connectivity/Droid/Connectivity.cs#L36 However, that does not fire any change event per default. Will look into this. Thanks for the report.

**Comment by NPadrutt** [comment]
I made some tests and noticed that in the sample it seems to work. But in my application the callback is not executed. The tests where executed on the same device. 
When I change the code to this it works for me:
          
```
            var globals = Mvx.Resolve<IMvxAndroidGlobals>();
            var manager =
                    globals.ApplicationContext.GetSystemService(Context.ConnectivityService)
                        .JavaCast<ConnectivityManager>();
            NetworkChanged(manager.ActiveNetworkInfo, false);
```
 Could that be a general solution or is there an issue with that?

**Comment by Cheesebaron** [comment]
Might be that we never get that callback we are listening for. Since IConnectivity is lazy instantiated, we should have IMvxAndroidGlobals at the time it gets instantiated, so there shouldn't be a problem changing it to the piece of code you've shown.

Make a PR :)
