### ISSUE TITLE
 Default constructor not found for type Cheesebaron.MvxPlugins.Connectivity.Touch.Plugin

### ISSUE THREAD

**Issue by softlion** [Cheesebaron/Cheesebaron.MvxPlugins#64]
When in release mode with LinkAll set to true, the app crashes.
Fix the crash in ConnectivityPluginBootstrap.cs by adding Preserve:

    /// <summary>
    /// Default constructor not found for type Cheesebaron.MvxPlugins.Connectivity.Touch.Plugin
    /// </summary>
    [Foundation.Preserve(AllMembers = true)]
    public class ConnectivityPluginBootstrapLinkerPleaseInclude
    {
        public void Include()
        {
            new Cheesebaron.MvxPlugins.Connectivity.Touch.Plugin();
        }
    }

**Comment by softlion** [comment]
There is the same problem in all your plugins

**Comment by Cheesebaron** [comment]
Right. Thanks for reporting this :)

**Comment by Cheesebaron** [comment]
As a workaround you can add something like this to your LinkerPleaseInclude.cs file:

```
private readonly List<IMvxPluginLoader> _loaders = new List<IMvxPluginLoader>
{
    Cheesebaron.MvxPlugins.Connectivity.PluginLoader.Instance,
    Cheesebaron.MvxPlugins.DeviceInfo.PluginLoader.Instance,
    Cheesebaron.MvxPlugins.Settings.PluginLoader.Instance
};

private readonly List<IMvxPlugin> _plugins = new List<IMvxPlugin>
{
    new Cheesebaron.MvxPlugins.Connectivity.Droid.Plugin(),
    new Cheesebaron.MvxPlugins.DeviceInfo.Droid.Plugin(),
    new Cheesebaron.MvxPlugins.Settings.Droid.Plugin()
};

public void Include(IMvxPluginLoader loader)
{
    foreach (var l in _loaders)
    {
        loader = l;
        loader.EnsureLoaded();
    }
}

public void Include(IMvxPlugin plugin)
{
    foreach (var l in _plugins)
    {
        plugin = l;
        plugin.Load();
    }
}
```

**Comment by softlion** [comment]
Already done but ty :)
