### ISSUE TITLE
System.IO.FileNotFoundException while bootstrapping Cheesebaron.MvxPlugins.DeviceInfo

### ISSUE THREAD

**Issue by turibbio** [Cheesebaron/Cheesebaron.MvxPlugins#66]
Problem: I get System.IO.FileNotFoundException while bootstrapping Cheesebaron.MvxPlugins.DeviceInfo in my Universal Windows project. 

Reference: Cheesebaron.MvxPlugins.DeviceInfo
Version: 2.2.2
Framework: uap10 (w/ netstandard 1.4)

Here's my bootstrap implementation:

`public class DeviceInfoBootstrap : MvxPluginBootstrapAction<PluginLoader>
{
}`

Following few exception details:
_Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.ni.dll
Additional information: Could not load file or assembly 'Cheesebaron.MvxPlugins.DeviceInfo.WindowsUWP, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified._

**Comment by Cheesebaron** [comment]
Thanks for reporting this. It seems like WindowsUWP is missing entirely from the NuGet package.

**Comment by turibbio** [comment]
I agree, I see just the WindowsCommon one

**Comment by Cheesebaron** [comment]
This should be fixed in 3.0.0 which is being built right now.

**Comment by turibbio** [comment]
I get this error: C:\Users\developer\.nuget\packages\Cheesebaron.MvxPlugins.DeviceInfo\3.0.0\lib\uap\Cheesebaron.MvxPlugins.DeviceInfo.WindowsUWP\Properties\WindowsUWP.rd.xml', I did a PR #67

**Comment by turibbio** [comment]
Closed for me!
